INSERT INTO `courses` (`name`, `code`, `credit`, `season`, `department_id`, `lecturer_id`)
VALUES
    ('ATATÜRK İLKELERİ VE İNKILAP TARİHİ I', 'ATA101', 2, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ENGLISH FOR ACADEMIC PURPOSES I', 'ENGL101', 4, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN DIŞI SEÇİMLİK DERS 1', 'HUKY001', 2, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN DIŞI SEÇİMLİK DERS 2', 'HUKY002', 2, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('HUKUK BAŞLANGICI', 'HUKY104', 3, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('MEDENİ HUKUK I (BAŞLANGIÇ-KİŞİLER HUKUKU)', 'HUKY113', 5, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ANAYASA HUKUKU I (GENEL ESASLAR)', 'HUKY123', 3, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ROMA HUKUKU I', 'HUKY136', 2, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('TÜRK DİLİ I', 'TÜRK101', 2, 'Birinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ATATÜRK İLKELERİ VE İNKILAP TARİHİ II', 'ATA102', 2, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ENGLISH FOR ACADEMIC PURPOSES II', 'ENGL102', 4, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('SEÇMELİ GÜZEL SANATLAR/İLK YARDIM', 'GSBHSH', 1, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN DIŞI SEÇİMLİK DERS 3', 'HUKY003', 2, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN DIŞI SEÇİMLİK DERS 4', 'HUKY004', 2, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('MEDENİ HUKUK II (AİLE HUKUKU)', 'HUKY114', 5, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ANAYASA HUKUKU II (TÜRK ANAYASA HUKUKU)', 'HUKY124', 4, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ROMA HUKUKU II', 'HUKY137', 3, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('TÜRK DİLİ II', 'TÜRK102', 2, 'İkinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ENGLISH FOR ACADEMIC PURPOSES III', 'ENGL201', 4, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 5', 'HUKY005', 4, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('BORÇLAR HUKUKU I', 'HUKY213', 4, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA HUKUKU I (GENEL HÜKÜMLER)', 'HUKY235', 3, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('TÜRK HUKUK TARİHİ', 'HUKY257', 3, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('İDARE HUKUKU I', 'HUKY260', 4, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('GENEL KAMU HUKUKU', 'HUKY263', 3, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('MİLLETLER ARASI KAMU HUKUKU I', 'HUKY291', 4, 'Üçüncü Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ENGLISH FOR ACADEMIC PURPOSES IV', 'ENGL202', 5, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 6', 'HUKY006', 4, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 7','HUKY007', 4, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('BORÇLAR HUKUKU II (GENEL HÜKÜMLER)', 'HUKY214', 5, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA HUKUKU II (GENEL HÜKÜMLER)', 'HUKY238', 4, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('İDARE HUKUKU II', 'HUKY261', 3, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('İNSAN HAKLARI HUKUKU I (MİLLETLERARASI İNSAN HAKLARI HUKUKU)', 'HUKY269', 2, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('MALİYE', 'HUKY286', 3, 'Dördüncü Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA HUKUKU I (ÖZEL HÜKÜMLER)', 'HUKY325', 4, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('VERGİ HUKUKU', 'HUKY351', 3, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('HUKUK FELSEFESİ', 'HUKY355', 2, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('EŞYA HUKUKU I', 'HUKY361', 4, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('BORÇLAR HUKUKU I (ÖZEL HÜKÜMLER)', 'HUKY371', 3, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('İDARİ YARGILAMA HUKUKU I', 'HUKY373', 3, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('MEDENİ USUL HUKUKU I', 'HUKY381', 4, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('TİCARET HUKUKU I (TİCARİ İŞLETME HUKUKU)', 'HUKY391', 4, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('TRANSLATION I', 'LENG305', 2, 'Beşinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 8', 'HUKY008', 4, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA HUKUKU II (ÖZEL HÜKÜMLER)', 'HUKY326', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('HUKUK SOSYOLOJİSİ', 'HUKY358', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('EŞYA HUKUKU II', 'HUKY362', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('İDARİ YARGILAMA HUKUKU II', 'HUKY370', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('BORÇLAR HUKUKU II (ÖZEL HÜKÜMLER)', 'HUKY380', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('MEDENİ USUL HUKUKU II', 'HUKY382', 4, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('TİCARET HUKUKU II (ŞİRKETLER HUKUKU)', 'HUKY392', 4, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('TRANSLATION II', 'LENG306', 3, 'Altıncı Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 9', 'HUKY009', 4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ADLİ TIP', 'HUKY411', 3, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('MİRAS HUKUKU I', 'HUKY450', 3, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('MİLLETLERARASI ÖZEL HUKUK I', 'HUKY465', 4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('İŞ HUKUKU', 'HUKY467', 4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('İCRA-İFLAS HUKUKU I (İCRA HUKUKU)', 'HUKY471',4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('TİCARET HUKUKU I (KIYMETLİ EVRAK HUKUKU)', 'HUKY481', 4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA USULÜ HUKUKU I', 'HUKY491', 4, 'Yedinci Yarıyıl (Güz)', 4, FLOOR(RAND() * 4) + 20),
    ('ALAN SEÇİMLİK DERS 10', 'HUKY010', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('MİRAS HUKUKU II', 'HUKY451', 3, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('AVRUPA KONSEYİ İNSAN HAKLARI HUKUKU VE TÜRKİYE', 'HUKY452', 2, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('MİLLETLERARASI ÖZEL HUKUK II', 'HUKY466', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('TOPLU İŞ HUKUKU', 'HUKY468', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('İCRA-İFLAS HUKUKU II (İFLAS HUKUKU)', 'HUKY472', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('TİCARET HUKUKU II (SİGORTA HUKUKU)', 'HUKY482', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20),
    ('CEZA USULÜ HUKUKU II', 'HUKY492', 4, 'Sekizinci Yarıyıl (Bahar)', 4, FLOOR(RAND() * 4) + 20);